[appearance]
	# Nom : Centrer la barre de recherche
	# Description : Déplace la barre de recherche de JEI en bas et au centre de l'écran.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	centerSearch = true

	# Nom : Hauteur maximum
	# Description : Hauteur maximum de l'interface de recette.
	# Valeurs valides : Any integer greater than or equal to 175
	# Valeur par défaut : 350
	recipeGuiHeight = 350


[cheating]
	# Nom : Mode Donner
	# Description : Choisit si JEI doit placer les objets directement dans l'inventaire ou les accrocher au curseur de la souris.
	# Valeurs valides : [INVENTORY, MOUSE_PICKUP]
	# Valeur par défaut : MOUSE_PICKUP
	giveMode = MOUSE_PICKUP

	# Nom : Tricher des objets dans la barre d'accès rapide via raccourcis
	# Description : Permet de tricher des objets dans la barre d'accès rapide en utilisant Maj + touches numériques.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	cheatToHotbarUsingHotkeysEnabled = false

	# Nom : Afficher les ingrédients masqués
	# Description : Permet d'afficher les ingrédients qui ne sont pas dans le menu créatif.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	showHiddenIngredients = false

	# Nom : Afficher les recettes de tags
	# Description : Affiche les recettes pour les tags d'ingrédients comme les tags d'objets et de blocs.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	showTagRecipesEnabled = false


[bookmarks]
	# Nom : Ajouter de nouveaux marque-pages
	# Description : Si elle est vraie, elle ajoute les nouveaux marque-pages au début de la liste des marque-pages. Si elle est fausse, elle ajoute les nouveaux marque-pages à la fin de la liste des marque-pages.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	addBookmarksToFrontEnabled = false

	# Nom : Glisser pour réorganiser les favoris
	# Description : Permet de glisser les favoris pour les réorganiser dans la liste.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	dragToRearrangeBookmarksEnabled = true


[tooltips]
	# Nom : Fonctionnalités des info-bulles de favoris
	# Description : Fonctionnalités supplémentaires pour les info-bulles de favoris.
	# Valeurs valides : A comma-separated list containing values of:
	# [PREVIEW, INGREDIENTS]
	# Valeur par défaut : PREVIEW
	bookmarkTooltipFeatures = PREVIEW

	# Nom : Maj pour les info-bulles de favoris
	# Description : Maintenir Maj pour afficher les fonctionnalités des info-bulles de favoris.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	holdShiftToShowBookmarkTooltipFeatures = true

	# Nom : Afficher les noms d'onglets créatifs
	# Description : Affiche les noms des onglets créatifs dans les info-bulles d'ingrédients.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	showCreativeTabNamesEnabled = false

	# Nom : Afficher le contenu des tags
	# Description : Affiche le contenu des tags dans les info-bulles lors du parcours des ingrédients de recettes.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	tagContentTooltipEnabled = true

	# Nom : Masquer le contenu des tags à un seul ingrédient
	# Description : Masque le contenu des tags dans les info-bulles lorsque le tag ne contient qu'un seul ingrédient.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	hideSingleTagContentTooltipEnabled = true

	# Nom : Résumé des ingrédients de recette
	# Description : Affiche un résumé des ingrédients nécessaires à une recette dans l'info-bulle de son ingrédient de sortie.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	enableRecipesGuiIngredientsSummary = false


[performance]
	# Nom : Recherche en faible mémoire
	# Description : Active le mode faible mémoire pour la recherche (rend la recherche plus lente mais utilise moins de RAM).
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	lowMemorySlowSearchEnabled = true


[lookups]
	# Nom : Rechercher le contenu des fluides
	# Description : Lors de la recherche de recettes avec des objets contenant des fluides, recherche également les recettes des fluides.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	lookupFluidContentsEnabled = false

	# Nom : Rechercher les tags de blocs d'objets
	# Description : Lors de la recherche par tags d'objets, inclut également les tags des blocs par défaut contenus dans les objets.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	lookupBlockTagsEnabled = true


[lookupHistory]
	# Nom : Activé
	# Description : Affiche ou masque la superposition de l'historique de recherche.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	enabled = true

	# Nom : Lignes maximales
	# Description : Nombre maximal de lignes affichées dans la superposition de l'historique de recherche.
	# Valeurs valides : An integer in the range [1, 7] (inclusive)
	# Valeur par défaut : 2
	maxRows = 2

	# Nom : Ingrédients maximum
	# Description : Nombre maximal d'ingrédients de l'historique de recherche à enregistrer.
	# Valeurs valides : An integer in the range [10, 1000] (inclusive)
	# Valeur par défaut : 100
	maxIngredients = 40

	# Nom : Côté d'affichage
	# Description : Côté de l'écran où afficher la superposition de l'historique de recherche.
	# Valeurs valides : [LEFT, RIGHT]
	# Valeur par défaut : LEFT
	displaySide = LEFT


[advanced]
	# Nom : Intercepter les erreurs de rendu
	# Description : Intercepte les erreurs de rendu des ingrédients moddés et tente de récupérer au lieu de planter.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	catchRenderErrorsEnabled = true


[input]
	# Nom : Délai de glisser
	# Description : Nombre de millisecondes avant qu'un long clic de souris soit considéré comme un glisser.
	# Valeurs valides : An integer in the range [0, 1000] (inclusive)
	# Valeur par défaut : 150
	dragDelayInMilliseconds = 150

	# Nom : Vitesse de défilement fluide
	# Description : Vitesse de défilement de la molette dans les boîtes à défilement fluide. Mesurée en pixels.
	# Valeurs valides : An integer in the range [1, 50] (inclusive)
	# Valeur par défaut : 9
	smoothScrollRate = 9


[sorting]
	# Nom : Étapes de tri des ingrédients
	# Description : Ordre de tri pour la liste des ingrédients.
	# Valeurs valides : A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# Valeur par défaut : MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	ingredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

	# Nom : Étapes de tri des recettes
	# Description : Ordre de tri pour les recettes affichées.
	# Valeurs valides : A comma-separated list containing values of:
	# [BOOKMARKED, CRAFTABLE]
	# Valeur par défaut : BOOKMARKED, CRAFTABLE
	recipeSorterStages = CRAFTABLE, BOOKMARKED


[search]
	# Nom : @NomDuMod
	# Description : Recherche par nom de mods (préfixe : @)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : REQUIRE_PREFIX
	modNameSearchMode = REQUIRE_PREFIX

	# Nom : #Tag
	# Description : Mode de recherche par tag (prefix: #)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : REQUIRE_PREFIX
	tagSearchMode = REQUIRE_PREFIX

	# Nom : $Infobulle
	# Description : Recherche par infobulles (préfixe : $)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : ENABLED
	tooltipSearchMode = ENABLED

	# Nom : ^Couleur
	# Description : Recherche par couleur d'objet (préfixe : ^)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : DISABLED
	colorSearchMode = DISABLED

	# Nom : &IDdeRessource
	# Description : Recherche par ID de ressource (préfixe : &)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : DISABLED
	resourceLocationSearchMode = DISABLED

	# Nom : %MenuCréatif
	# Description : Recherche par nom du Menu Créatif (préfixe : %)
	# Valeurs valides : [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valeur par défaut : DISABLED
	creativeTabSearchMode = DISABLED

	# Nom : Recherche avancée par infobulle
	# Description : Rechercher dans les info-bulles avancées (visibles avec F3 + H).
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	searchAdvancedTooltips = false

	# Nom : Rechercher les IDs de mods
	# Description : Rechercher les IDs de mods en plus des noms de mods.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	searchModIds = true

	# Nom : Rechercher les alias de mods
	# Description : Rechercher les alias de mods (noms alternatifs) ajoutés par les plugins, en plus des noms de mods.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	searchModAliases = true

	# Nom : Rechercher les noms courts de mods
	# Description : Rechercher par les premières lettres abrégées du nom d'un mod.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	searchShortModNames = true

	# Nom : Rechercher les alias d'ingrédients
	# Description : Rechercher les alias d'ingrédients (noms alternatifs) ajoutés par les plugins, en plus des noms d'ingrédients.
	# Valeurs valides : [true, false]
	# Valeur par défaut : true
	searchIngredientAliases = true


[ingredientList]
	# Nom : Lignes maximales
	# Description : Nombre maximal de lignes affichées.
	# Valeurs valides : An integer in the range [1, 100] (inclusive)
	# Valeur par défaut : 16
	maxRows = 20

	# Nom : Colonnes maximales
	# Description : Nombre maximal de colonnes affichées.
	# Valeurs valides : An integer in the range [2, 100] (inclusive)
	# Valeur par défaut : 9
	maxColumns = 10

	# Nom : Alignement horizontal
	# Description : Alignement horizontal de la liste d'ingrédients dans la zone disponible.
	# Valeurs valides : [LEFT, CENTER, RIGHT]
	# Valeur par défaut : RIGHT
	horizontalAlignment = RIGHT

	# Nom : Alignement vertical
	# Description : Alignement vertical de la liste d'ingrédients dans la zone disponible.
	# Valeurs valides : [TOP, CENTER, BOTTOM]
	# Valeur par défaut : TOP
	verticalAlignment = TOP

	# Nom : Visibilité de navigation
	# Description : Visibilité des boutons de page en haut. Utilisez AUTO_HIDE pour ne les afficher que lorsqu'il y a plusieurs pages.
	# Valeurs valides : [ENABLED, AUTO_HIDE, DISABLED]
	# Valeur par défaut : ENABLED
	buttonNavigationVisibility = ENABLED

	# Nom : Dessiner l'arrière-plan de l'interface
	# Description : Activez ceci pour dessiner une texture d'arrière-plan derrière la liste d'ingrédients.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	drawBackground = false


[bookmarkList]
	# Nom : Lignes maximales
	# Description : Nombre maximal de lignes affichées.
	# Valeurs valides : An integer in the range [1, 100] (inclusive)
	# Valeur par défaut : 16
	maxRows = 12

	# Nom : Colonnes maximales
	# Description : Nombre maximal de colonnes affichées.
	# Valeurs valides : An integer in the range [2, 100] (inclusive)
	# Valeur par défaut : 9
	maxColumns = 9

	# Nom : Alignement horizontal
	# Description : Alignement horizontal de la liste de favoris dans la zone disponible.
	# Valeurs valides : [LEFT, CENTER, RIGHT]
	# Valeur par défaut : LEFT
	horizontalAlignment = LEFT

	# Nom : Alignement vertical
	# Description : Alignement vertical de la liste de favoris dans la zone disponible.
	# Valeurs valides : [TOP, CENTER, BOTTOM]
	# Valeur par défaut : TOP
	verticalAlignment = TOP

	# Nom : Visibilité de navigation
	# Description : Visibilité des boutons de page en haut. Utilisez AUTO_HIDE pour ne les afficher que lorsqu'il y a plusieurs pages.
	# Valeurs valides : [ENABLED, AUTO_HIDE, DISABLED]
	# Valeur par défaut : ENABLED
	buttonNavigationVisibility = ENABLED

	# Nom : Dessiner l'arrière-plan de l'interface
	# Description : Activez ceci pour dessiner une texture d'arrière-plan derrière la liste de favoris.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	drawBackground = false


