[debug]
	# Nom : Mode de débogage
	# Description : Utile seulement pour les développeurs de JEI, ajoute des milliers d'objets et de recettes factices.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	debugMode = false

	# Nom : Interfaces de débogage
	# Description : Active le mode des interfaces de débogage
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	debugGuis = false

	# Nom : Entrées de débogage
	# Description : Active le mode des entrées de débogage
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	debugInputs = false

	# Nom : Info-bulles d'informations de débogage
	# Description : Ajoute des informations de débogage aux info-bulles d'ingrédients lorsque les info-bulles avancées sont activées.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	debugInfoTooltipsEnabled = false

	# Nom : Activer les objets de test de plantage
	# Description : Ajoute des ingrédients à JEI qui plantent intentionnellement, pour aider à déboguer JEI.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	crashingTestItemsEnabled = false

	# Nom : jei.config.debug.debug.crashingTestRecipesEnabled
	# Description : jei.config.debug.debug.crashingTestRecipesEnabled.description
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	crashingTestRecipesEnabled = false

	# Nom : Journaliser les statistiques de l'arbre de recherche
	# Description : Journalise les informations sur les arbres de suffixes utilisés pour la recherche, pour aider à déboguer JEI.
	# Valeurs valides : [true, false]
	# Valeur par défaut : false
	logSuffixTreeStats = false


