#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 16 02:44:15 CET 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound.zip
