#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 19 16:39:49 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound.zip
